#!/usr/bin/env bash
# This script install and configure HAproxy on your Ib-01 server.

apt-get -y update
apt-get -y install haproxy
echo "
frontend web_servers
	bind *:80
	mode http
	default_backend web_backend
backend web_backend
	balance roundrobin
	server 148050-web-01 34.229.186.196:80 check
	server 148050-web-02 54.209.120.56:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
